### ISSUE TITLE
conf/metadata.php is missing some settings

### ISSUE THREAD

**Issue by fiwswe** [mprins/dokuwiki-plugin-openlayersmap#33]
## environment

  - php version: 8.0.23 (irrelevant)
  - dokuwiki version: 2022-07-31a "Igor" (irrelevant)
  - plugin version / date: 2022-08-31
  - list of any other plugins (apart from bundled plugins): irrelevant, note: [sprintDoc Template](https://www.dokuwiki.org/template:sprintdoc) is being used (might affect the details of the HTML but not the basic issue)
  
## expected behaviour

No settings should be listed at the bottom of the configuration page as undefined. Why have these as settings and then not provide UI for setting them?

## actual behaviour

Added at the bottom of the config page `…&do=admin&page=config`:
```
<h1 id="undefined_settings">Undefined Settings<a href="#undefined_settings" class="anchor"><svg viewBox="2 2 22 22"><path d="M10.59,13.41C11,13.8 11,14.44 10.59,14.83C10.2,15.22 9.56,15.22 9.17,14.83C7.22,12.88 7.22,9.71 9.17,7.76V7.76L12.71,4.22C14.66,2.27 17.83,2.27 19.78,4.22C21.73,6.17 21.73,9.34 19.78,11.29L18.29,12.78C18.3,11.96 18.17,11.14 17.89,10.36L18.36,9.88C19.54,8.71 19.54,6.81 18.36,5.64C17.19,4.46 15.29,4.46 14.12,5.64L10.59,9.17C9.41,10.34 9.41,12.24 10.59,13.41M13.41,9.17C13.8,8.78 14.44,8.78 14.83,9.17C16.78,11.12 16.78,14.29 14.83,16.24V16.24L11.29,19.78C9.34,21.73 6.17,21.73 4.22,19.78C2.27,17.83 2.27,14.66 4.22,12.71L5.71,11.22C5.7,12.04 5.83,12.86 6.11,13.65L5.64,14.12C4.46,15.29 4.46,17.19 5.64,18.36C6.81,19.54 8.71,19.54 9.88,18.36L13.41,14.83C14.59,13.66 14.59,11.76 13.41,10.59C13,10.2 13,9.56 13.41,9.17Z"></path></svg></a></h1>
<fieldset><div class="table"><table class="inline"><tbody><tr><td class="label"><span title="$meta['default_baselyr']">$conf['plugin']['openlayersmap']['default_baselyr']</span></td><td>No setting metadata.</td></tr><tr><td class="label"><span title="$meta['default_id']">$conf['plugin']['openlayersmap']['default_id']</span></td><td>No setting metadata.</td></tr><tr><td class="label"><span title="$meta['default_lat']">$conf['plugin']['openlayersmap']['default_lat']</span></td><td>No setting metadata.</td></tr><tr><td class="label"><span title="$meta['default_lon']">$conf['plugin']['openlayersmap']['default_lon']</span></td><td>No setting metadata.</td></tr><tr><td class="label"><span title="$meta['default_summary']">$conf['plugin']['openlayersmap']['default_summary']</span></td><td>No setting metadata.</td></tr></tbody></table></div></fieldset>
```

## steps to reproduce actual behavior

Open the admin configuration page`…&do=admin&page=config` and scroll to the bottom.

### error log

None

### debug log

Nothing relevant

**Comment by mprins** [comment]
these have been contributed in https://github.com/mprins/dokuwiki-plugin-openlayersmap/commit/c8eb13626ece0cdbb2369662b8c76ea8fa800c3a (actually https://sourceforge.net/p/dokuwikispatial/code/751/ ) and are marked with an "invisible" comment to hide them on purpose; I don't recall the discussion from that time I had with Aleksej Kozlov at the time. Looking at the code these seem to be fallback values.

I do not see those "No setting metadata." in any of my wiki's (both Igor and Hogfather)

**Comment by fiwswe** [comment]
I see. But why have a configuration setting (as opposed to a constant in code) when it isn't configurable in the UI?

I don't understand exactly what values/types would be appropriate but it should be fairly easy to add the relevant lines in `metadata-php`. Something like this seems to work:
```
$meta ['default_id']               = array(
	'string'
);
$meta ['default_lat']              = array(
	'numeric'
);
$meta ['default_lon']              = array(
	'numeric'
);
$meta ['default_baselyr']          = array(
	'string'
);
$meta ['default_summary']          = array(
	'string'
);

```
Of course the localized descriptions are still missing and you could mention there that these settings are somewhat off-limits.


I think DW does not have an _invisible_ config setting type because it makes no sense.

**Comment by fiwswe** [comment]
Oh, and I have the `allowDebug` flag on. Without it the extra `Undefined Settings` section is not displayed.
