### ISSUE TITLE
OpenLayers map crashes when no single dot is added / Solved 

### ISSUE THREAD

**Issue by johngnl** [mprins/dokuwiki-plugin-openlayersmap#34]
## environment

  - php version: 7.4
  - dokuwiki version: Igor
  - plugin version / date: 2022-09-02
  - list of any other plugins (apart from bundled plugins): quite a lot, not needed because I fixed the issue.
  
## expected behaviour
A OpenLayers map without a single dot, however centered around the indicated lat and lon coordinates given in the opening tag:
Example: 
`<olmap id="olMap_example" width="550px" height="450px" lat="51.3680" lon="6.1403" zoom="14" statusbar="1" controls="1" poihoverstyle="0" baselyr="OpenStreetMap" gpxfile="" kmlfile="" geojsonfile="" summary="" ></olmap>`

This worked in both an earlier version of OpenLayersMap and DokuWiki.

## actual behaviour
A crash showing error message:
''TypeError: Argument 1 passed to syntax_plugin_openlayersmap_olmap::extractPoints() must be of the type string, null given''

## steps to reproduce actual behaviour
Copy the sample code above onto a page. However, see fix below.

### error log

```
TypeError: Argument 1 passed to syntax_plugin_openlayersmap_olmap::extractPoints() 
must be of the type string, null given
```

### FIX
File: dw_base/lib/plugins/openlayersmap/syntax/olmap.php
```
    public function handle($match, $state, $pos, Doku_Handler $handler): array {
	...
        $gmap          = $this->extractParams($str_params);
	if (is_null($str_points)) $str_points = ''; // JohnG - added
        $overlay       = $this->extractPoints($str_points);
	...
```
Now it works again as it used to:

![image](https://user-images.githubusercontent.com/95931496/197618203-c3823b5c-04a4-4eaf-9907-98de830e45d4.png)

**Comment by mprins** [comment]
> plugin version / date: 2022-09-02

This version does not exist, the latest version is 2022-08-31

Please provide a pull request, preferably with a unit test

**Comment by johngnl** [comment]
Thanks for your excellent plugin, first of all.

Sorry, I must have copied it from the wong location.
**plugin version / date:  2022-08-31**

> Please provide a pull request, preferably with a unit test

I don't know how that works. 

I fixed the issue in my installed version however as indicated. Hoping it might help other users.
