### ISSUE TITLE
OpenLayers map plugin 2022-10-31 interferes with other DW UI Elements

### ISSUE THREAD

**Issue by fiwswe** [mprins/dokuwiki-plugin-openlayersmap#39]
## environment

  - php version: 7.4.32
  - dokuwiki version: 2020-07-29a "Hogfather"
  - plugin version / date: 2022-10-31
  - list of any other plugins (apart from bundled plugins): 
Add New Page — Last updated on 2015-11-02
Advanced DokuWiki — Last updated on 2022-09-23
Blog — Last updated on 2020-09-19
Changes Plugin — Last updated on 2022-09-07
charpicker — Last updated on 2022-09-06
color syntax plugin — Last updated on 2022-10-19
discussion plugin — Last updated on 2021-12-31
DocNavigation plugin — Last updated on 2022-10-06
Extended List syntax — Last updated on 2016-07-26
folded plugin — Last updated on 2020-09-24
geoPHP plugin for DokuWiki — Last updated on 2022-09-02
include plugin — Last updated on 2022-01-23
Login/Logout logging plugin — Last updated on 2020-11-16
Meta plugin — Last updated on 2021-10-16
Move plugin — Last updated on 2022-01-23
nspages plugin — Last updated on 2022-09-08
Pagelist Plugin — Last updated on 2022-09-28
PHP Wikify — Last updated on 2020-06-05
Searchindex Manager — Last updated on 2020-06-21
Tag Plugin — Last updated on 2022-10-02
User History Manager Plugin — Last updated on 2021-02-07
Wrap Plugin — Last updated on 2022-08-10
WRAP Plus — Last updated on 2021-11-12

sprintDoc Template — Last updated on 2021-11-09

## expected behaviour
a) Admin -> Extension manager: UI for selecting View options (enabled, disabled, updateable) should be present.
b) Editor: UI Elements for formatting should be present. 

## actual behaviour
a) Admin Extension manager: UI for selecting View options (enabled, disabled, updateable) is missing.
b) Editor: UI Elements for formatting are missing. 

## steps to reproduce actual behaviour
Update  OpenLayers plugin to latest version (2022-10-31).

Disabling the plugin restores the functionality.

### error log
_none_

### debug log
_none_

**Comment by mprins** [comment]
> sprintDoc Template — Last updated on 2021-11-09

do these problems occur with the default template?

**Comment by fiwswe** [comment]
Yes they do. sprintDoc or default Dokuwiki template makes no difference.

**Comment by mprins** [comment]
I have been unable to reproduce your problem on any of my DW instances, admittedly I only run Igor or newer versions on PHP 8 and I don't have the same list of plugins installed.

Your problem seems like a client-side/javascript issue TBH as all those features that are not working for you are rendered using Javascript AFAIK.

**Comment by fiwswe** [comment]
Version 2023-03-05 and Safari Version 16.3 (18614.4.6.1.6) macOS 13.2.1 Ventura (22D68) do not show the issue.

Note: An older Version of Safari still has the problem: Version 11.1.2 (11605.3.8.1) OS X 10.11.6 El Capitan (15G22010) While the last version of Brave Browser still available for the same machine has no issues.

This makes a client-side/JS issue very plausible.

There is probably not enough interest in supporting (much) older browsers so I guess this issue will most likely not get fixed.
