### ISSUE TITLE
Multiple maps on one page

### ISSUE THREAD

**Issue by peterfromearth** [mprins/dokuwiki-plugin-openlayersmap#48]
If I use more then one map on a page the maps are located right after each other

## environment

  - php version: 7.4.33
  - dokuwiki version: 2022-07-31a "Igor"
  - plugin version / date: 2022-12-22
  - list of any other plugins (apart from bundled plugins): template: bootstrap3 (but also with default template)
  
## expected behaviour
the map should be displayed where they are defined

## actual behaviour
all maps are located at the location of the first map.

## steps to reproduce actual behaviour
define more than one map on different location on one page

### error log

```
ERRORS
```

### debug log

```
DEBUG
```

**Comment by mprins** [comment]
Your report is missing key information for debugging and/or analysis.
Please provide the exact syntax/code you used.

**Comment by peterfromearth** [comment]
Ok found my problem. I did not used the `id` attribute to define different ids.

I used it like this
```
====== Map1 ======
<olmap width="600px" height="400px" lat="31.5822" lon="-6.5074" zoom="7" controls="1" baselyr="OpenStreetMap" gpxfile=":blog:xxx.gpx">
</olmap>

====== Map2 ======
<olmap width="600px" height="400px" lat="31.5822" lon="-6.5074" zoom="7" controls="1" baselyr="OpenStreetMap" gpxfile=":blog:yyy.gpx">
</olmap>
```
after I added `id` attribute it worked.
```
====== Map1 ======
<olmap id="a" width="600px" height="400px" lat="31.5822" lon="-6.5074" zoom="7" controls="1" baselyr="OpenStreetMap" gpxfile=":blog:xxx.gpx">
</olmap>

====== Map2 ======
<olmap id="b" width="600px" height="400px" lat="31.5822" lon="-6.5074" zoom="7" controls="1" baselyr="OpenStreetMap" gpxfile=":blog:yyy.gpx">
</olmap>
```

(you could define a random id if none is defined)

thanks for the plugin!

**Comment by mprins** [comment]
documentation is clear on using `id` : https://www.dokuwiki.org/plugin:openlayersmap#syntax_usage
using a random value was never a possibility in the past where the id was needed as an extension point for other plugins. not sure if it's possible now.
